### ISSUE TITLE
Cromwell bug

### ISSUE THREAD

**Issue by fakukikza** [Drofseh/IFA3_ACRE2_COMPAT#12]
**Arma 3 Version: STABLE
**IFA Version: STABLE

**CBA Version: STABLE

**ACE3 Version: STABLE

**ACRE2 Version: STABLE
**Mods: 
- IFA
- CBA
- ACE3
- ACRE2
```

**Description:**
The cromwell have a bug, and have only a one slot to driver, no commander slots and gunner

**Steps to reproduce:**
Just put a Cromwell from IFA_AIO_LITE

**Where did the issue occur?**
All

**Placed Modules:**
None

**RPT log file:**

**Comment by Drofseh** [comment]
Please fill out the issue template properly, including version numbers and your rpt file.
